export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
export const FETCH_FOOD_DETAILS_SUCCESS = 'FETCH_FOOD_DETAILS_SUCCESS';

export const ADD_FOOD_TO_PLAN = 'ADD_FOOD_TO_PLAN';
export const CALCULATE_FOOD = 'CALCULATE_FOOD';
export const CALCULATE_FOOD_PLAN = 'CALCULATE_FOOD_PLAN';
export const DELETE_FOOD = 'DELETE_FOOD';
export const DELETE_PLAN = 'DELETE_PLAN';